export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_END = 'GET_CATEGORIES_END';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_BLOGS_START = 'GET_BLOGS_START';
export const GET_BLOGS_END = 'GET_BLOGS_END';
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_END = 'CREATE_POST_END';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

