export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_END = 'GET_CATEGORIES_END';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

export const GET_BLOGS_START = 'GET_BLOGS_START';
export const GET_BLOGS_END = 'GET_BLOGS_END';
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_END = 'CREATE_POST_END';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const CREATE_CATEGORY_START = 'CREATE_CATEGORY_START';
export const CREATE_CATEGORY_END = 'CREATE_CATEGORY_END';
export const CREATE_CATEGORY_ERROR = 'CREATE_CATEGORY_ERROR';

export const SEARCH_START = 'SEARCH_START';
export const SEARCH_END = 'SEARCH_END';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_END = 'DELETE_POST_END';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_END = 'EDIT_POST_END';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';

export const SET_CURRENT_POST = 'SET_CURRENT_POST';

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

